name = "AccessibleModels"
uuid = "4b3c8bd9-8c05-441a-9330-31ce8207a5fd"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.6"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extensions]
DistributionsExt = "Distributions"
IntervalSetsExt = "IntervalSets"
MakieExt = "Makie"
MonteCarloMeasurementsPigeonsExt = ["MonteCarloMeasurements", "Pigeons"]
OptimizationExt = "Optimization"
PigeonsExt = "Pigeons"
TablesExt = "Tables"

[compat]
AccessorsExtra = "0.1.98"
DataPipes = "0.3.18"
Distributions = "0.25.120"
FlexiMaps = "0.1.28"
IntervalSets = "0.7.11"
Makie = "0.22, 0.24"
MonteCarloMeasurements = "1.4.7"
Optimization = "4.4.0"
Pigeons = "0.4.9"
Printf = "1"
Reexport = "1.2.2"
Tables = "1.12.1"
julia = "1.10"
